<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ClienteSeeder extends Seeder
{
    public function run(): void
    {
        $clientes = [
            [
                'cliente_nombre' => 'María José',
                'cliente_apellido' => 'Reyes Padilla',
                'cliente_dni' => '0501-1995-01234',
                'cliente_estado_civil' => 'Casada',
                'cliente_telefono' => '9876-5001',
                'cliente_direccion' => 'Col. Trejo, Calle 5, Casa 12, San Pedro Sula',
                'cliente_numero_hijos' => 2,
                'cliente_nombres_hijos' => 'Sofía Rivera Reyes, Mateo Rivera Reyes',
                'cliente_profesion' => 'Licenciada en Administración',
                'cliente_lugar_trabajo' => 'BANPAÍS',
                'cliente_direccion_trabajo' => 'Bulevar Morazán, San Pedro Sula',
                'cliente_telefono_trabajo' => '2556-1000',
                'cliente_salario_mensual' => 28000.00,
                'cliente_estado' => 'activo',
            ],
            [
                'cliente_nombre' => 'Pedro Antonio',
                'cliente_apellido' => 'Mejía López',
                'cliente_dni' => '0501-1990-04567',
                'cliente_estado_civil' => 'Divorciado',
                'cliente_telefono' => '9876-5002',
                'cliente_direccion' => 'Residencial Los Ángeles, Calle 8, Casa 5, SPS',
                'cliente_numero_hijos' => 1,
                'cliente_nombres_hijos' => 'Valeria Mejía Pineda',
                'cliente_profesion' => 'Ingeniero Civil',
                'cliente_lugar_trabajo' => 'Constructora del Valle',
                'cliente_direccion_trabajo' => 'Zona Industrial, SPS',
                'cliente_telefono_trabajo' => '2557-2000',
                'cliente_salario_mensual' => 35000.00,
                'cliente_estado' => 'activo',
            ],
            [
                'cliente_nombre' => 'Ana Cecilia',
                'cliente_apellido' => 'García Hernández',
                'cliente_dni' => '0501-1993-07890',
                'cliente_estado_civil' => 'Soltera',
                'cliente_telefono' => '9876-5003',
                'cliente_direccion' => 'Col. Satélite, Bloque 3, Casa 8, SPS',
                'cliente_numero_hijos' => 3,
                'cliente_nombres_hijos' => 'Carlos Mendoza García, Lucía Mendoza García, Diego Mendoza García',
                'cliente_profesion' => 'Maestra de Educación Primaria',
                'cliente_lugar_trabajo' => 'Escuela República de Honduras',
                'cliente_direccion_trabajo' => 'Barrio El Centro, SPS',
                'cliente_telefono_trabajo' => '2558-3000',
                'cliente_salario_mensual' => 15000.00,
                'cliente_estado' => 'activo',
            ],
            [
                'cliente_nombre' => 'Bernarda Aracely',
                'cliente_apellido' => 'Paz Guzmán',
                'cliente_dni' => '0501-1988-05678',
                'cliente_estado_civil' => 'Divorciada',
                'cliente_telefono' => '9876-5004',
                'cliente_direccion' => 'Col. Bella Vista, Calle 10, Casa 3, SPS',
                'cliente_numero_hijos' => 2,
                'cliente_nombres_hijos' => 'Andrés Paz Mejía, Pamela Paz Mejía',
                'cliente_profesion' => 'Contadora Pública',
                'cliente_lugar_trabajo' => 'Deloitte Honduras',
                'cliente_direccion_trabajo' => 'Bulevar Morazán, Edif. Plaza, SPS',
                'cliente_telefono_trabajo' => '2559-4000',
                'cliente_salario_mensual' => 32000.00,
                'cliente_estado' => 'activo',
            ],
            [
                'cliente_nombre' => 'Luis Enrique',
                'cliente_apellido' => 'Mendoza Rivera',
                'cliente_dni' => '0501-1985-03456',
                'cliente_estado_civil' => 'Casado',
                'cliente_telefono' => '9876-5005',
                'cliente_direccion' => 'Col. Los Andes, Calle 2, Casa 15, SPS',
                'cliente_numero_hijos' => 3,
                'cliente_nombres_hijos' => 'Ana Mendoza Pérez, Luis Mendoza Pérez, Carla Mendoza Pérez',
                'cliente_profesion' => 'Médico General',
                'cliente_lugar_trabajo' => 'Hospital Mario Catarino Rivas',
                'cliente_direccion_trabajo' => 'Boulevard del Norte, SPS',
                'cliente_telefono_trabajo' => '2560-5000',
                'cliente_salario_mensual' => 45000.00,
                'cliente_estado' => 'activo',
            ],
            [
                'cliente_nombre' => 'Karla Patricia',
                'cliente_apellido' => 'Sandoval Torres',
                'cliente_dni' => '0501-1996-02345',
                'cliente_estado_civil' => 'Soltera',
                'cliente_telefono' => '9876-5006',
                'cliente_direccion' => 'Residencial El Carmen, Casa 8, SPS',
                'cliente_numero_hijos' => 1,
                'cliente_nombres_hijos' => 'Jorge Sandoval Martínez',
                'cliente_profesion' => 'Abogada',
                'cliente_lugar_trabajo' => 'Bufete Sandoval y Asociados',
                'cliente_direccion_trabajo' => 'Barrio Guamilito, 3ra Calle, SPS',
                'cliente_telefono_trabajo' => '2561-6000',
                'cliente_salario_mensual' => 38000.00,
                'cliente_estado' => 'activo',
            ],
            [
                'cliente_nombre' => 'Roberto Carlos',
                'cliente_apellido' => 'Murillo Díaz',
                'cliente_dni' => '0501-1982-06789',
                'cliente_estado_civil' => 'Casado',
                'cliente_telefono' => '9876-5007',
                'cliente_direccion' => 'Col. San Carlos, Calle 7, Casa 22, SPS',
                'cliente_numero_hijos' => 2,
                'cliente_nombres_hijos' => 'Sofía Murillo López, Roberto Murillo López',
                'cliente_profesion' => 'Arquitecto',
                'cliente_lugar_trabajo' => 'Estudio Murillo Arquitectos',
                'cliente_direccion_trabajo' => 'Bulevar del Sur, SPS',
                'cliente_telefono_trabajo' => '2562-7000',
                'cliente_salario_mensual' => 42000.00,
                'cliente_estado' => 'activo',
            ],
            [
                'cliente_nombre' => 'Diana Patricia',
                'cliente_apellido' => 'Ortiz Medina',
                'cliente_dni' => '0501-1994-08901',
                'cliente_estado_civil' => 'Soltera',
                'cliente_telefono' => '9876-5008',
                'cliente_direccion' => 'Col. Montecristo, Calle 4, Casa 10, SPS',
                'cliente_numero_hijos' => 0,
                'cliente_nombres_hijos' => null,
                'cliente_profesion' => 'Ingeniera Industrial',
                'cliente_lugar_trabajo' => 'Grupo Karim Tex',
                'cliente_direccion_trabajo' => 'Zona Libre, Puerto Cortés',
                'cliente_telefono_trabajo' => '2563-8000',
                'cliente_salario_mensual' => 48000.00,
                'cliente_estado' => 'activo',
            ],
            [
                'cliente_nombre' => 'Jorge Luis',
                'cliente_apellido' => 'Rivera Murillo',
                'cliente_dni' => '0501-1979-04568',
                'cliente_estado_civil' => 'Casado',
                'cliente_telefono' => '9876-5009',
                'cliente_direccion' => 'Col. San José, Calle 12, Casa 7, SPS',
                'cliente_numero_hijos' => 4,
                'cliente_nombres_hijos' => 'María Rivera Paz, José Rivera Paz, Pedro Rivera Paz, Ana Rivera Paz',
                'cliente_profesion' => 'Comerciante',
                'cliente_lugar_trabajo' => 'Distribuidora Rivera',
                'cliente_direccion_trabajo' => 'Mercado El Dandy, SPS',
                'cliente_telefono_trabajo' => '2564-9000',
                'cliente_salario_mensual' => 25000.00,
                'cliente_estado' => 'activo',
            ],
            [
                'cliente_nombre' => 'Sandra Elizabeth',
                'cliente_apellido' => 'Cruz Flores',
                'cliente_dni' => '0501-1997-01235',
                'cliente_estado_civil' => 'Soltera',
                'cliente_telefono' => '9876-5010',
                'cliente_direccion' => 'Aldea Las Palmas, Casa 3, SPS',
                'cliente_numero_hijos' => 2,
                'cliente_nombres_hijos' => 'Luis Cruz Martínez, Kevin Cruz Martínez',
                'cliente_profesion' => 'Ama de casa',
                'cliente_lugar_trabajo' => null,
                'cliente_direccion_trabajo' => null,
                'cliente_telefono_trabajo' => null,
                'cliente_salario_mensual' => 0.00,
                'cliente_estado' => 'activo',
            ],
            [
                'cliente_nombre' => 'Héctor Daniel',
                'cliente_apellido' => 'Vargas Pinto',
                'cliente_dni' => '0501-1986-01236',
                'cliente_estado_civil' => 'Divorciado',
                'cliente_telefono' => '9876-5011',
                'cliente_direccion' => 'Col. Moderna, Calle 6, Casa 18, SPS',
                'cliente_numero_hijos' => 1,
                'cliente_nombres_hijos' => 'Camila Vargas Rivas',
                'cliente_profesion' => 'Piloto de aeronaves',
                'cliente_lugar_trabajo' => 'Aerolínea CM Airlines',
                'cliente_direccion_trabajo' => 'Aeropuerto Villeda Morales, SPS',
                'cliente_telefono_trabajo' => '2565-2000',
                'cliente_salario_mensual' => 55000.00,
                'cliente_estado' => 'activo',
            ],
            [
                'cliente_nombre' => 'Dilcia Nohemí',
                'cliente_apellido' => 'Quintanilla Paz',
                'cliente_dni' => '0501-1992-06780',
                'cliente_estado_civil' => 'Casada',
                'cliente_telefono' => '9876-5012',
                'cliente_direccion' => 'Col. Villa Olímpica, Casa 4, SPS',
                'cliente_numero_hijos' => 2,
                'cliente_nombres_hijos' => 'Fernando Toro Quintanilla, Gabriela Toro Quintanilla',
                'cliente_profesion' => 'Licenciada en Mercadeo',
                'cliente_lugar_trabajo' => 'Cervecería Hondureña',
                'cliente_direccion_trabajo' => 'Bulevar Morazán, SPS',
                'cliente_telefono_trabajo' => '2566-4000',
                'cliente_salario_mensual' => 33000.00,
                'cliente_estado' => 'activo',
            ],
        ];

        DB::table('clientes')->insert($clientes);
    }
}
